remote: false

experienceLevel:
  internship: False
  entry: True
  associate: False
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: False
  internship: false
  other: false
  volunteer: false

Salary: 80000

date:
  all time: false
  month: false
  week: True
  24 hours: False

positions:
  - Software engineer

locations:
  - United States

apply_once_at_company: true

distance: 100

company_blacklist:
  - SpaceEx
  - Tesla

title_blacklist:
  - WebDeveloper
  - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 1000

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
